### ISSUE TITLE
"Mod manager" button styling is off

### ISSUE THREAD

**Issue by thomaswp** [Timberborn-Modding-Central/ModManager#54]
The main menu "Mod manager" button has the wrong styling in the latest version of Timberborn for me:

![image](https://github.com/Timberborn-Modding-Central/ModManager/assets/1750176/346f46a6-cd45-4442-9f10-f49ed398830a)

I fixed it by changing `new Button()` to `new LocalizableButton()` in [Patches.cs](https://github.com/Timberborn-Modding-Central/ModManager/blob/main/ModManagerUI/Patches.cs#L21).

**Comment by KYPremco** [comment]
Fix with the PR #53
